// import { useState } from 'react';
import { api } from '../api/client';
import axios from 'axios';



export function useB2Upload() {
    // We remove internal progress state to allow caller to manage it per file
    // but we keep error for general reporting if needed (though caller might want per-file error)

    const uploadFile = async (file: File, onProgress?: (percent: number) => void, category?: string): Promise<{ success: boolean; error?: string }> => {
        try {
            // 1. Get Intent
            const intentRes = await api.post('/cms/media/upload-intent', {
                filename: file.name,
                size_bytes: file.size,
                mime_type: file.type,
                category // Optional: "videos", "images", "kyc", "thumbnails"
            });
            const { media_asset_id, upload_url, auth_token } = intentRes.data;

            // 2. Upload to B2
            // B2 requires filename in URL for some apis, but get_upload_url returns a generic one.
            // When using b2_upload_file, we POST to the URL.
            // The filename is specified in the header 'X-Bz-File-Name'.
            // The 'Authorization' header is the authToken.
            // B2 expects SHA1 checksum in 'X-Bz-Content-Sha1', 'do_not_verify' is allowed for speed.

            // NOTE: The B2 `get_upload_url` endpoint returns a URL that expects a POST request.
            // Headers: Authorization, X-Bz-File-Name, Content-Type, Content-Length, X-Bz-Content-Sha1

            // Encode filename: B2 docs recommend normal filenames, SDK handles it.
            // But we are using axios direct.
            // The storage_key IS the file name we want in the bucket.


            await axios.post(upload_url, file, {
                headers: {
                    'Authorization': auth_token,
                    // B2 requires the file name to be URL-encoded (including slashes)
                    'X-Bz-File-Name': encodeURIComponent(intentRes.data.storage_key), // Use the key generated by backend
                    'Content-Type': file.type || 'b2/x-auto',
                    'X-Bz-Content-Sha1': 'do_not_verify'
                },
                onUploadProgress: (p) => {
                    const percent = p.total ? Math.round((p.loaded * 100) / p.total) : 0;
                    onProgress?.(percent);
                }
            });

            // 3. Complete
            await api.patch(`/cms/media/${media_asset_id}/complete`, {
                status: 'uploaded'
            });

            return { success: true };
        } catch (err: any) {
            console.error("Upload error:", err);
            // B2 returns { code, message, status } in body
            const errorMsg = err.response?.data?.message || err.response?.data?.detail || "Upload failed";
            return { success: false, error: errorMsg };
        }
    };

    return { uploadFile };
}
